# Generated by Django 4.0.4 on 2022-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('price_ht', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire HT')),
                ('price_ttc', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire TTC')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
    ]
