# Generated by Django 4.0.4 on 2022-04-22 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_productattribute_productattributevalue_productitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product_attribute',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 22, 8, 42, 31, 803747, tzinfo=utc), verbose_name='Date création'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Offline'), (1, 'Online'), (2, 'Out of stock')], default=0),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
