# Generated by Django 4.0.4 on 2022-04-22 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_alter_product_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Identifiant du  client')),
                ('id_produit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Identifiant du  produit')),
                ('date_ajout', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 22, 14, 36, 10, 568066, tzinfo=utc), verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Panier',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 22, 14, 36, 10, 567488, tzinfo=utc), verbose_name='Date création'),
        ),
    ]
