# Generated by Django 4.0.4 on 2022-04-22 22:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('backoffice', '0007_alter_panier_date_ajout_alter_product_date_creation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserManage',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='panier',
            name='date_ajout',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 22, 22, 31, 7, 521147, tzinfo=utc), verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 22, 22, 31, 7, 520181, tzinfo=utc), verbose_name='Date création'),
        ),
    ]
