# Generated by Django 4.0.4 on 2022-04-22 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_alter_panier_date_ajout_alter_product_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='date_ajout',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 22, 22, 40, 51, 642720, tzinfo=utc), verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 22, 22, 40, 51, 642130, tzinfo=utc), verbose_name='Date création'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
