# Generated by Django 4.0.4 on 2022-04-22 23:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backoffice', '0010_alter_panier_date_ajout_alter_product_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='date_ajout',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 22, 23, 5, 52, 41696, tzinfo=utc), verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 22, 23, 5, 52, 40971, tzinfo=utc), verbose_name='Date création'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('customer_address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('customer_city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('customer_country', models.SmallIntegerField(choices=[(0, 'CI'), (1, 'BF'), (2, 'MI')], default=0)),
                ('customer_state', models.SmallIntegerField(choices=[(0, 'CI'), (1, 'BF'), (2, 'MI')], default=0)),
                ('customer_zip_code', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
